<a href="https://colab.research.google.com/github/itzThillaiC/Tensorflow_models/blob/main/LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**        LSTM for Time series analysis**

In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten


In [23]:
def prepare_data(time_data,n_features):
  x,y=[],[]
  for i in range(len(time_data)):
    end_ix=i+n_features
    if end_ix >len(time_data)-1:
      break
    seq_x,seq_y=time_data[i:end_ix],time_data[end_ix]
    x.append(seq_x)
    y.append(seq_y)
  
  return np.array(x),np.array(y)
    


In [22]:
time_data=[110,125,133,146,158,172,187,196,210]
n_steps=3
x,y=prepare_data(time_data,n_features)

In [8]:
print(x),print(y)

[[110 125 133]
 [125 133 146]
 [133 146 158]
 [146 158 172]
 [158 172 187]
 [172 187 196]]
[146 158 172 187 196 210]


(None, None)

In [24]:
n_features=1
x=x.reshape((x.shape[0],x.shape[1],n_features))

In [25]:
x.shape

(8, 1, 1)

LSTM model

In [26]:
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
